DROP TABLE IF EXISTS inbound_messages;
DROP TABLE IF EXISTS inbox_cursors;
DROP TABLE IF EXISTS exports;
DROP TABLE IF EXISTS scheduled_tasks;
DROP TABLE IF EXISTS email_events;
DROP TABLE IF EXISTS tracking_links;
DROP TABLE IF EXISTS campaigns;
DROP TABLE IF EXISTS email_templates;
DROP TABLE IF EXISTS contacts;
